stages:
- pre-scans
- test

gitleaks:
  stage: test
  allow_failure: true

exe:
  tags:
    - nixos-starkify-runner
  script:
    - nix-shell --run "cabal build exe:starkify"
    - nix-shell --run "cabal run starkify --help"

testfiles:
  stage: test
  tags:
    - nixos-starkify-runner
  script:
    - nix-shell --run "cabal build --enable-tests"
    - nix-shell --run "cabal test"
    - nix-shell --run "cabal run testfiles"

additional_arith_test:
  stage: test
  tags:
    - nixos-starkify-runner
  script:
    - nix-shell --run "cabal test --test-option=--qc-max-success=1000"
  only:
    - master

include:
  - project: security/security-ci-cd-templates
    file: /qredo-security.gitlab-ci.yml
    ref: master
