stages:
- test

include:
  - project: 'devops/gitlab-ci-templates'
    ref: master
    file: .gitlab-ci.yml

gitleaks:
  stage: test
  allow_failure: true

testfiles:
  stage: test
  tags:
    - nixos-starkify-runner
  script:
    - nix-shell --run "cabal test --test-option=--qc-max-success=10000"
    - nix-shell --run "cabal run testfiles"

additional_arith_test:
  stage: test
  tags:
    - nixos-starkify-runner
  script:
    - nix-shell --run "cabal test --test-option=--qc-max-success=20000"
  only:
    - master
